#
# CircleCI 2.0
#
version: 2
jobs:
  package:
    docker:
      - image: circleci/python
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Package
          command: |
            ./package.sh
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - versions/*
            - release.sh
  release:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Release
          command: |
            pwd
            ls -al
            ./release.sh

workflows:
  version: 2
  apply:
    jobs:
      - package
      - release:
          requires:
            - package
  nightly:
    jobs:
      - package
      - release:
          requires:
            - package
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
